from dotenv import load_dotenv

from core.config.env_helpers import (
    env_bool as _env_bool,
)
from core.config.env_helpers import (
    env_float as _env_float,
)
from core.config.env_helpers import (
    env_int as _env_int,
)
from core.config.env_helpers import (
    env_str as _env_str,
)

load_dotenv()  # Safety fallback — main.py también lo llama explícitamente


class OperationalConfig:
    """Configuración de infraestructura, conectividad y sistema."""

    VERSION = "v118.7-PRO"
    BINANCE_API_KEY = _env_str("BINANCE_API_KEY")
    BINANCE_API_SECRET = _env_str("BINANCE_API_SECRET")

    PAPER_MODE = _env_bool("PAPER_MODE", True)
    ALLOW_REAL_TRADING = _env_bool("ALLOW_REAL_TRADING", False)
    PAPER_INITIAL_BALANCE = _env_float("PAPER_INITIAL_BALANCE", 1000.0)
    USE_TESTNET = _env_bool("USE_TESTNET", False)
    EXECUTION_BACKEND = _env_str("EXECUTION_BACKEND", "live")
    SHADOW_SIM_LATENCY_MIN_MS = _env_int("SHADOW_SIM_LATENCY_MIN_MS", 200)
    SHADOW_SIM_LATENCY_MAX_MS = _env_int("SHADOW_SIM_LATENCY_MAX_MS", 500)
    SHADOW_SIM_REJECT_RATE = _env_float("SHADOW_SIM_REJECT_RATE", 0.03)
    SHADOW_SIM_PARTIAL_FILL_RATE = _env_float("SHADOW_SIM_PARTIAL_FILL_RATE", 0.25)
    SHADOW_SIM_PARTIAL_COMPLETE_RATE = _env_float("SHADOW_SIM_PARTIAL_COMPLETE_RATE", 0.50)
    SHADOW_SIM_PRICE_OUT_OF_RANGE_RATE = _env_float("SHADOW_SIM_PRICE_OUT_OF_RANGE_RATE", 0.05)
    SHADOW_SIM_MIN_PARTIAL_RATIO = _env_float("SHADOW_SIM_MIN_PARTIAL_RATIO", 0.30)
    PARTIAL_FILL_TIMEOUT_SECONDS = _env_int("PARTIAL_FILL_TIMEOUT_SECONDS", 300)
    PENDING_SEND_STALE_SECONDS = _env_int("PENDING_SEND_STALE_SECONDS", 30)
    GLOBAL_ENTRY_COOLDOWN_SECONDS = _env_int("GLOBAL_ENTRY_COOLDOWN_SECONDS", 300)
    SIGNAL_COOLDOWN_SHADOW_SECONDS = _env_int("SIGNAL_COOLDOWN_SHADOW_SECONDS", 60)
    HARD_SL_ATTACH_MAX_RETRIES = _env_int("HARD_SL_ATTACH_MAX_RETRIES", 3)
    CANCEL_ALL_DEGRADED_WINDOW_SECONDS = _env_int("CANCEL_ALL_DEGRADED_WINDOW_SECONDS", 300)
    CANCEL_ALL_DEGRADED_QUARANTINE_EVENTS = _env_int("CANCEL_ALL_DEGRADED_QUARANTINE_EVENTS", 3)
    CANCEL_ALL_DEGRADED_QUARANTINE_SECONDS = _env_int("CANCEL_ALL_DEGRADED_QUARANTINE_SECONDS", 900)
    NO_PRICE_EXIT_ESCALATION_SECONDS = _env_int("NO_PRICE_EXIT_ESCALATION_SECONDS", 180)
    NO_PRICE_EXIT_MIN_ESCALATION_SECONDS = _env_int("NO_PRICE_EXIT_MIN_ESCALATION_SECONDS", 45)
    NO_PRICE_ALLOW_MARKET_EXIT = _env_bool("NO_PRICE_ALLOW_MARKET_EXIT", False)
    SMART_EXIT_THRESHOLD_REAL = _env_float("SMART_EXIT_THRESHOLD_REAL", 0.80)
    SMART_EXIT_THRESHOLD_SHADOW = _env_float("SMART_EXIT_THRESHOLD_SHADOW", 0.30)
    MAX_ENTRY_SL_PCT = _env_float("MAX_ENTRY_SL_PCT", 3.00)
    STOP_LOSS_ATR_MODIFIER = _env_float("STOP_LOSS_ATR_MODIFIER", 2.0)

    # --- ADOPCIÓN DE HUÉRFANOS ---
    ORPHAN_ADOPTION_MIN_SIZE_USD = _env_float("ORPHAN_ADOPTION_MIN_SIZE_USD", 10.0)
    ORPHAN_ADOPTION_MAX_SIZE_USD = _env_float("ORPHAN_ADOPTION_MAX_SIZE_USD", 10000.0)
    ORPHAN_SL_ATR_MULTIPLIER = _env_float("ORPHAN_SL_ATR_MULTIPLIER", 2.0)
    ORPHAN_SL_PERCENTAGE = _env_float("ORPHAN_SL_PERCENTAGE", 0.02)

    ENABLE_UI = _env_bool("ENABLE_UI", True)
    FORCE_UI = _env_bool("FORCE_UI", False)
    SCAN_INTERVAL = 300
    LOG_FILE = "sniper.log"
    LOG_LIMIT = 100

    TELEGRAM_TOKEN = _env_str("TELEGRAM_TOKEN")
    TELEGRAM_CHAT_ID = _env_str("TELEGRAM_CHAT_ID")
    TELEGRAM_ADMIN_IDS = _env_str("TELEGRAM_ADMIN_IDS")
    TELEGRAM_RATE_LIMIT_SECONDS = _env_float("TELEGRAM_RATE_LIMIT_SECONDS", 1.2)
    SMART_EXIT_FEE_NOISE_MAX_MINUTES = _env_float("SMART_EXIT_FEE_NOISE_MAX_MINUTES", 45)
    SMART_EXIT_FEE_GUARD_ENABLED = _env_bool("SMART_EXIT_FEE_GUARD_ENABLED", False)
    REQUIRE_GHOST_MODEL_FOR_TRADING = _env_bool("REQUIRE_GHOST_MODEL_FOR_TRADING", False)

    # --- GITHUB PROJECTS KANBAN ---
    GITHUB_TOKEN = _env_str("GITHUB_TOKEN")
    GITHUB_PROJECT_ID = _env_str("GITHUB_PROJECT_ID")
    GITHUB_PROJECT_OWNER = _env_str("GITHUB_PROJECT_OWNER")
    GITHUB_PROJECT_NUMBER = _env_int("GITHUB_PROJECT_NUMBER", 1)

    # --- [DEPRECADO] Lista estática de pares — YA NO SE USA ---
    PAIRS: list[str] = []
    SECONDARY_PAIRS: list[str] = []
    SECONDARY_SCAN_INTERVAL_SECONDS = 4 * 3600

    SECTORS: dict[str, list[str]] = {
        "L1": ["BTC", "ETH", "SOL", "ADA", "DOT", "AVAX"],
        "AI": ["FET", "AGIX", "OCEAN", "NEAR", "ICP"],
        "DEFI": ["UNI", "AAVE", "CRV", "MKR", "COMP"],
        "MEME": ["DOGE", "SHIB", "PEPE", "FLOKI"],
        "GAME": ["SAND", "MANA", "AXS", "GALA"],
    }

    # --- SISTEMA DE TRIAJE CINÉTICO ---
    TOP_TRIAGE_COUNT = _env_int("TOP_TRIAGE_COUNT", 30)
    TRIAGE_SPREAD_MAX = 0.0005
    TRIAGE_TIMEOUT_SECONDS = 4
    TRIAGE_MAX_WORKERS = _env_int("TRIAGE_MAX_WORKERS", 16)
    TRIAGE_CANDIDATE_POOL_MULTIPLIER = _env_int("TRIAGE_CANDIDATE_POOL_MULTIPLIER", 3)
    TRIAGE_MAX_CANDIDATE_POOL = _env_int("TRIAGE_MAX_CANDIDATE_POOL", 100)
    TRIAGE_RVOL_EMA_ALPHA = 0.02
    LATENCY_VETO_MS = 4500
    LATENCY_QUARANTINE_SECONDS = 300

    ENTRY_SPREAD_VETO_THRESHOLD = 0.0005

    REGIME_SPREAD_THRESHOLDS = {
        "BULL_TREND": 0.0010,
        "BEAR_TREND": 0.0008,
        "RANGE": 0.0005,
    }

    SYMBOL_CONTROLS_REFRESH_SECONDS = _env_int("SYMBOL_CONTROLS_REFRESH_SECONDS", 1800)
    SYMBOL_REDUCED_SIZE_MULTIPLIER = _env_float("SYMBOL_REDUCED_SIZE_MULTIPLIER", 0.5)

    # --- LÍMITES DE FETCHING ---
    CANDLE_FETCH_LIMIT = 500
    FETCH_TRIAL_LIMIT = 3
    MAX_SYMBOLS = 100
    MIN_CANDLE_HISTORY = 200
    MAX_REAL_PAIRS = 20
    MAX_SHADOW_PAIRS = 20
